name: eatbay_admin
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  cloud_firestore: ^3.2.1
  cupertino_icons: ^1.0.2
  firebase_auth: ^3.4.1
  firebase_core: ^1.19.1
  firebase_storage: ^10.3.1
  flutter:
    sdk: flutter
  flutter_facebook_auth: ^4.4.0
  get: ^4.6.5
  google_fonts: ^3.0.1
  google_sign_in: ^5.3.3
  image_picker: ^0.8.5+3
  twitter_login: ^4.2.3

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - assets/images/
